### ISSUE TITLE
Extranet: faire une zone "Mes dossiers en cours"

### ISSUE THREAD

**Issue by pboko** [vteco/pre#10]
C'est un nouvel onglet sur la homepage des gestionnaires.
Ca affiche une liste de tous les dossiers au statut "incomplet" dont on est le gestionnaire
(réutiliser le template de liste de dossiers existant)

On peut également, en bonus, mettre un autre onglet "Tous mes dossiers" qui affiche la liste totale des dossiers du gestionnaire, tous statuts confondus

**Comment by nicolasvte** [comment]
A gérer par la refonte de l'extranet
