### ISSUE TITLE
Extranet :Le préremplissage d'ASH ne marche pas

### ISSUE THREAD

**Issue by JonathanVTE** [vteco/pre#102]
A l'enregistrement il y a un probleme sur le style du document
![bug](https://cloud.githubusercontent.com/assets/11160254/6823750/6f69c120-d2eb-11e4-8186-c6b6e66f50ca.PNG)

**Comment by lindavte** [comment]
@JonathanVTE : sur quel travaux on a le bug ?  (non reproduit )
