### ISSUE TITLE
Email de prise en compte d'une demande de contact depuis pro.primesenergie

### ISSUE THREAD

**Issue by JonathanVTE** [vteco/pre#103]
L'email envoyé après une demande de contact contient des liens qui pointent vers des 404.

Idéalement, il faudrait voir si il est possible d'envoyer un mail différent pour les demandes de contact depuis les différents sous-domaines.

![bug2](https://cloud.githubusercontent.com/assets/11160254/6827815/19b4de6c-d30a-11e4-91a2-73606210d022.png)

**Comment by pboko** [comment]
svn 8578
