### ISSUE TITLE
Envoi de ASH en PJ depuis l'extranet

### ISSUE THREAD

**Issue by pboko** [vteco/pre#11]
envoi d'email via "modèle vierge sans bouton"
avec copie au pro et joindre l'AFT cochés 

=> Pas de PJ chez le client
=> vérifier si le bug est toujours d'actualité

**Comment by lindavte** [comment]
A voir avec pierre

**Comment by pboko** [comment]
En fait c'est normal mais uniquement lorsqu'on envoie un email d'incomplet.
En effet dans ce cas, le client reçoit un email différent de celui du pro. Il reçoit "nous avons contacté votre artisan pour valider votre dossier...", et ce mail n'a pas besoin de PJ

=> il faut envoyer la PJ , sauf s'il s'agit d'un mail d'incomplet
=> on a l'info dans EmailMessageForm->send()

**Comment by lindavte** [comment]
svn 8359
