### ISSUE TITLE
Définir des valeurs par défaut pour des questions ASH

### ISSUE THREAD

**Issue by pboko** [vteco/pre#142]
ex: 
- fenêtre ou porte fenetre => fenetre
- propriétaire final ou maître d'ouvrage => propriétaire final

**Comment by lindavte** [comment]
ASH_PRO_MOA: 
    UPDATE  work_ash_field SET  defaultval =  '1' WHERE  ash_fiel_id =49
ASH_OWNER
   UPDATE  work_ash_field SET  defaultval =  '1' WHERE  ash_fiel_id =46
