### ISSUE TITLE
Extranet: impossible de créer un dossier pour un particulier

### ISSUE THREAD

**Issue by pboko** [vteco/pre#170]
Le bouton "simulateur" amène vers le site entreprises.primesenergie.fr
Le fait de cliquer ensuite sur "particulier" les amène à modifier leur propre compte, et à se substituer au client.

=> il faudrait deux liens "simualteurs", un particulier et un entreprise. idéalement le choix se ferait dans une popup, comme c'est le cas sur www.certificatsdenergie.fr au clic sur le bouton principal

**Comment by lindavte** [comment]
Le bouton simulateur amène vers le site entreprises.primesenergie.fr uniquement pour les personne qui on un profile entreprise. 
Pour le service SAV le bouton amène sur le simulateur de frontend et non pas sur entreprise
