### ISSUE TITLE
faire le schéma de la table contrôle

### ISSUE THREAD

**Issue by pboko** [vteco/pre#174]
CONTROLE
- ash_field_id
- controle_type:
  - egality
  - greater
  - lower
  - function
  - date_egality
  - date_greater
  - date_lower
- target_value
- target_input => peut être un tableau, séparés par des virgules. Sur qui le controle s'applique
- target_func_name
- controle_group
  - ash
  - facture
  - general

CONTROLE_TRAVAUX
- controle_id
- eligible_work_id

**Comment by lindavte** [comment]
svn  8747
