### ISSUE TITLE
Remplir les contrôle des travaux fenêtre

### ISSUE THREAD

**Issue by pboko** [vteco/pre#175]
Section A:
Date du devis après date d'incitation
Date de facture après date du devis
ASH_ACFLAG = 1 (<=> Oui)
Uw = function() {
  si type fenetre = fenetre de toiture:
      Uw <= 1.5
  sinon
      Uw <= 1.3 et Sw >= 0.3
      OU
     Uw <= 1.7 et Sw >= 0.36
}
Sw = function() {
  si type fenetre = fenetre de toiture:
      Sw >= 0.36
  sinon
      Uw <= 1.3 et Sw >= 0.3
      OU
     Uw <= 1.7 et Sw >= 0.36
}

Section B:
SIRET: voir s'il existe => VOIR A LA FIN
ASH_USER_NO_SIREN: 
   si = 1, SIREN doit être non rempli
   si = 0, SIREN doit être rempli
ASH_USER_CITY:
  vérifier la cohérence avec le code postal (si possible, grâce aux infos lampiris) => VOIR A LA FIN
ASH_USER_EDITION_DATE >= facture

Section C
ASH_PRO_SIRET: essayer de contrôler  => VOIR A LA FIN
ASH_PRO_MOA: si = 2, les champs suivants doivent être remplis:
   ASH_PRO2_SIRET, ASH_PRO2_SOCIAL_NAME, ASH_PRO2_LAST_NAME, ASH_PRO2_FIRST_NAME
ASH_PRO_EDITION_DATE: >= date facture

Section facture:
Rajouter deux questions : "Si oui, précisez le Uw/Sw"
Si oui
INV_UW = ASH_UW

Siren(INV_SIRET) = Siren(ASH_SIRET)

INV_NOM = 1
INV_CEE = 0 => le controle contient un lien vers un doc
INV_OPERATION = 1

Section CONTROLE
Toutes les réponses doivent être des 1

**Comment by lindavte** [comment]
svn 8758, 8760
