### ISSUE TITLE
Pouvoir choisir l'obligé dans l'interface pro

### ISSUE THREAD

**Issue by pboko** [vteco/pre#19]
Cette fonctionnalité doit être disponible uniquement pour notre service => créer un nouveau groupe.

Pour les membres de ce groupe, on doit avoir:
- un formulaire PartnerSimulationForm qui permet de choisir le mwh_price (cf SavSimulationForm)
- dans la page de formulaire, sous le champ mwh_price, écrire le nom de l'obligé actuel rattaché au partenaire
- à côté du nom de l'obligé, un lien "changer d'obligé"
- une page de modification de l'obligé du partenaire

**Comment by lindavte** [comment]
svn revision : 8319
