### ISSUE TITLE
Validation demande sur site mobile

### ISSUE THREAD

**Issue by pboko** [vteco/pre#20]
Les valeurs possibles pour la question 'ACFLAG' sont les anciennes:
- avant on demandait l'année de construction
- maintenant on demande si le bâtiment est existant depuis plus de deux ans.

Le titre des input_val correspondant a été changé en BDD:
- avant 1975 => Non
- après 1975 et existant depusi plus de deux ans  => Oui

Mais le site mobile affiche toujours les anciennes valeurs possibles pour cette question.
Il faut donc se baser sur les input_val existants aujourd'hui en base de donnée.

=> vérifier en faisant une demande, une fois le correctif en prod, depuis iphone blackberry et android

**Comment by lindavte** [comment]
revision svn : 8282
