### ISSUE TITLE
Emailing parrainage sur base primes validées

### ISSUE THREAD

**Issue by nicolasvte** [vteco/pre#22]
Renvoyer "parlez-en autour de vous, profitez encore de primes énergie pour financer de nouveaux travaux"

Parrainage ? => "Recevez 10 € si vous ramenez un nouveau client"

**Comment by pboko** [comment]
C'est une offre de parrainage.
Pour un exemple de template, rechercher dans nos boîtes mails "boursorama", ou "Exceptionnel : 150 euros offerts par parrainage", ou consulter l'emailing en ligne sur: http://fibs2.boursorama.com/nl/jsp/m.jsp?c=7bac543f8337530a15

**Comment by pboko** [comment]
Créer une page dans l'espace perso "Parrainer votre entourage", avec un champ adresse email du filleul
Créer deux emails:
- un reçu par le filleul "machin vous a parrainé. Créez un dossier et touchez vous xx €, lui yy €. Votre code de parrainage est le ..."
- un envoyé à tous les dossiers validés, avec "parrainez votre entourage, et touchez yy € !", à la date d'envoi du chèque + 6 jours

Rajouter un champ "Avez-vous un code de parrainage?" dans le formulaire de coordonnées, lors de la création de la prime. Si oui, afficher un champ de saisie du code.

Le code sera enregistré en BDD, et liera le parrain avec un seul filleul. Une fois utilisé, ce code est donc bloqué sur un seul filleul.

Après il faudra voir la logistique de suivi des bonus de parrainage, de notre côté et du leur. Et voir si on fait un chèque, un virement...

Cette tâche dépend de vteco/pre#23 : enregistrer la date d'envoi du chèque

**Comment by nicolasvte** [comment]
EMAILING SIMPLE. --> 12 / 20

OK POUR UN COUPON : 

Pour vous:

Un CHEQUE CADEAU égal à 5% du montant de la Prime énergie validée de votre filleul dans la limite de 50 €.

D'autres Travaux en perspective ? Demandez de nouvelles primes?

A déposer sur votre compte bancaire

**Comment by pboko** [comment]
Exemple d'emailing : http://www.ecoavie.fr/portfolio/parrainage/
