### ISSUE TITLE
Enregistrer la date d'envoi du chèque

### ISSUE THREAD

**Issue by pboko** [vteco/pre#23]
Dans la table dossier. Cette date doit doit remplacer le flag actuel "is_prime_sent", et on l'appelle "check_dispatch_off_date".

Il faut donc remplacer la méthode "isPrimeSent", qui vérifiait le flag stocké en base, par un test sur le champ "check_dispatch_date"

**Comment by lindavte** [comment]
Revision svn : 8275, 8276, 8277
