### ISSUE TITLE
EXPORT AVIA: pouvoir filtrer par obligé

### ISSUE THREAD

**Issue by pboko** [vteco/pre#235]

**Comment by lindavte** [comment]
Faire plusieurs URLs d'export:
/export/avia?period=2(ou 3)
/export/vte?period=2(ou 3)

Et /exportavia?period=2 doit être redirigée sur /export/avia?period=2

La route devient /export/:oblige_name
Et dans l'action on a un tableau statique:
avia => 1, 5
vte => 2, 4, 6  (ce sont les oblige_ids)
antargaz => 3
- mettre un paramètre en plus dans la méthode qui récupère les dossiers pour l'export (obligeIds)
  => c'est le 1er paramètre, car il est obligatoire

**Comment by lindavte** [comment]
svn 9438
