### ISSUE TITLE
Espace pro avec remise: la date de devis doit pouvoir être avant l'incitation

### ISSUE THREAD

**Issue by pboko** [vteco/pre#241]
En effet dans le cas de la remise, le devis fait office d'incitation => il est donc normal que le dossier soit créé après.

Il faut donc pouvoir créer le dossier avec une date de devis antérieure à celle du jour.
Et modifier le contrôle de date de devis en conséquence, en vérifiant s'il s'agit ou non d'un dossier avec remise.

**Comment by lindavte** [comment]
svn 9128
