### ISSUE TITLE
Bug sur l'edition d'un partenaire

### ISSUE THREAD

**Issue by JonathanVTE** [vteco/pre#264]
Quand j'essaye d'éditer le partenaire Ecopuissance3 depuis le backend, j'ai l'erreur suivante (cf screenshot).
Pour info le partenaire n'a pas d'user associé, c'est peut être l'origine du problème.

![invalidargumentexception- widget user does not exist](https://cloud.githubusercontent.com/assets/11160254/8380487/52024c22-1c26-11e5-9345-126027bab3d1.png)

**Comment by lindavte** [comment]
Bug non reproduit meme avec un partenaire sans utilisateur

**Comment by lindavte** [comment]
Mise à jour de la version de symfony 1.4.10 => 1.4.20
