### ISSUE TITLE
Bug Email Artisan d'un dossier validé - A corriger avant prochain envoi de chèque

### ISSUE THREAD

**Issue by JonathanVTE** [vteco/pre#317]
SUjet du Mail : Votre client à reçu un chèque de Prime Energie 

L'email est envoyé au même pro pour tous les dossiers validés un même jour (et non pas au pro du dossier concerné)

**Comment by lindavte** [comment]
ok

**Comment by lindavte** [comment]
w

**Comment by lindavte** [comment]
ss
