### ISSUE TITLE
Mettre plus en avant les liens particuliers/entreprise

### ISSUE THREAD

**Issue by pboko** [vteco/pre#32]
![image](https://cloud.githubusercontent.com/assets/1906061/6433237/f70e6bba-c069-11e4-8249-0f4ca1b47ffa.png)

Ce n'est pas assez visible.

Idée : faire quelque chose proche de ce qui existe sur http://www.energie-info.fr/
![image](https://cloud.githubusercontent.com/assets/1906061/6433244/3c4a96ea-c06a-11e4-9497-96fb67dca253.png)

**Comment by lindavte** [comment]
svn revision : 8311
