### ISSUE TITLE
Rechercher tous les autres cas d'utilisation des champs profile finagaz

### ISSUE THREAD

**Issue by pboko** [vteco/pre#323]
Adatper le code intelligement, au besoin

Utiliser au maximum les méthodes isUGINewClient plutot que isAgNewClient...
idem existingClient..
Idem isUGI...

rechercher :
- isAgNewClient
- isAgExistingClient
- isAntargazClient ou isAgClient
- isAntargazForm
- isFinagazForm
  ....

**Comment by lindavte** [comment]
svn 9639

**Comment by lindavte** [comment]
svn 9640

**Comment by lindavte** [comment]
svn 9644
