### ISSUE TITLE
DEADLINE 03/03 : Jeu concours à mettre en place

### ISSUE THREAD

**Issue by pboko** [vteco/pre#33]
Doit être en ligne pou le 3 mars

Il s'agit d'une popup en fin de demande de primes énergie, uniquement sur www.primesenergie.fr
=> pas sur l'iframe
=> pas sur le site entreprise

Du coup il faut désactiver la popup crédit travaux.

La popup avait déjà été mise en place dans le commit 6021. Il faut faire exactement la même chose, en mettant les bonnes dates dans le code pour qu'à la fin du jeu concours la popup de crédit se réactive automatiquement, et quel celle de jeu concours disparaisse.

URL du jeu : https://www.facebook.com/primesenergie.fr/app_592882127435623
Dates pour la pop up : du 03/03/15 au 05/04/2015
Cadeau : Chèque de 100€
Texte pop up : Participez à notre jeu concours et tentez de gagner un chèque de 100 € !

**Comment by pboko** [comment]
Nouvelle image de la popup de jeu concours: 

![jeu-mobile](https://cloud.githubusercontent.com/assets/1906061/6433357/eae243c2-c06c-11e4-891a-f00f5f1f347b.png)

**Comment by lindavte** [comment]
SVN revison : 8308
