### ISSUE TITLE
Intégrer la question "offre duo" dans les différents formulaires

### ISSUE THREAD

**Issue by pboko** [vteco/pre#332]
Tous ceux qui utilisent le champ "fz_new_client", "fz_existing_client".. doivent poser cette question.

Surtout à la création de dossier, et dans l'espace admin finagaz (celui qui leur permet de modifier un user) => ils vont en avoir besoin, et vont mettre à jour régulièrement des infos utilisateurs.

**Comment by lindavte** [comment]
svn 9665
