### ISSUE TITLE
Bug footer sur les horaires d'ouverture

### ISSUE THREAD

**Issue by pboko** [vteco/pre#34]
Il y a deux horaires différents qui sont précisés dans le footer:
![image](https://cloud.githubusercontent.com/assets/1906061/6439445/13969960-c0d3-11e4-876e-86cf9812ffac.png)

Il faut laisser uniquement: "01 40 13 40 13 (9h - 17h sans interruption)"

**Comment by lindavte** [comment]
svn revision : 8315
