### ISSUE TITLE
Etape Finalize => Bulle d'aide sur l'offre duo

### ISSUE THREAD

**Issue by pboko** [vteco/pre#351]
Reprendre le texte déjà écrit + le picto d'aide de l'extranet V2

**Comment by pboko** [comment]
Question: Offre duo : Souhaitez-vous souscrire à notre offre Duo Rénovation ?
(mettre une bulle d'aide:  Offre Duo: en choissant un appareil proposé par nos partenaires, bénéficiez en plus d'une remise sur le matériel installé, ainsi que d'une majoration de la Prime Eco-Déclic Finagaz !)

**Comment by lindavte** [comment]
svn 9728
