### ISSUE TITLE
Masquer le curseur de rémunération dans l'interface pro

### ISSUE THREAD

**Issue by pboko** [vteco/pre#36]
![image](https://cloud.githubusercontent.com/assets/1906061/6439904/f8505772-c0d7-11e4-98a9-85a7dc8cc9b7.png)

On veut par défaut le masquer, et qu'il y ait un lien "modifier la répartition de la prime", qui permette d'afficher cette zone

**Comment by lindavte** [comment]
svn revision : 8332
