### ISSUE TITLE
Le renvoi du mail d'incitation ne marche pas

### ISSUE THREAD

**Issue by pboko** [vteco/pre#38]
Depuis l'espace perso on ne peut plus recevoir l'ASH par email.

Soit on le répare, soit on supprime la fonctionnalité  ; vu qu'il peut télécharger son ASH directement avec le lien au-dessus, on se demande à quoi cela sert, finalement.

![image](https://cloud.githubusercontent.com/assets/1906061/6461077/1094cb9a-c19d-11e4-801a-8dd2584ad58f.png)

**Comment by lindavte** [comment]
svn : 8352
