### ISSUE TITLE
Mettre à jour les dossiers lorsqu'on met à jour l'utilisateur

### ISSUE THREAD

**Issue by pboko** [vteco/pre#390]
mettre un updatePrecaDossiers() dans l'utilisateur, qui mette à jour les dossiers sous certaines conditions:
- preca_level du dossier != de de celui du user
- dossier au plus complet
- dossier->isPrecaEligible

Cette méthode met à jour le dossier avec les nouvelles infos preca_level et nb_hab_foyer, et recalcule le bon montant au kwh, et recalcule la prime

**Comment by lindavte** [comment]
svn 10488
