### ISSUE TITLE
Mettre à jour dossier->isPrecaEligible()

### ISSUE THREAD

**Issue by pboko** [vteco/pre#391]
Pas de partenaire, ou Partenaire est préca-éligible 
Vérifier si ce test n'était pas déjà fait quand on faisait isPrecaEligible()

vérifier qu'il appartient au groupe de travaux précarité
- rajouter une méthode à partner "isPrecaEligible", qui teste si le partenaire et son parent ne sont pas antargaz, ni finagaz

**Comment by lindavte** [comment]
svn 10485
