### ISSUE TITLE
Ordre de règlement (Antargaz + nous) : prendre en compte la remise 

### ISSUE THREAD

**Issue by pboko** [vteco/pre#408]
Il faut que le bénéficiaire soit le pro dans l'ordre de règlement
Il faut s'assurer que les chèques prennent bien en compte la TVA
Il faut vérifier que le paiement n'est possible que si la facture a été reçue

**Comment by lindavte** [comment]
ordre de reglement VTE : svn 11235

**Comment by lindavte** [comment]
Ordre de reglement antargaz : svn 11239
