### ISSUE TITLE
Dupliquer la landing page créée pour PrimesEnergie.fr et l’adaptée à Antargaz.

### ISSUE THREAD

**Issue by pboko** [vteco/pre#419]
- Adapter le wording : 10 % deviennent 50 € supp.
- Prime énergie bonifiée devient « Prime énergie maitrisée bonifiée »
- Les liens vers l’espace perso (téléchargement d’ASH) renvoient vers l’espace perso d’Antargaz

**Comment by lindavte** [comment]
svn 11332 (sur la branche qualifpreca)
svn 11333
