### ISSUE TITLE
Préparer une tache d’envoi d’e-mail aux dossiers ANTARGAZ suivants:

### ISSUE THREAD

**Issue by pboko** [vteco/pre#420]
- Dossiers « Validé – PréValidé - Complet » Non déposé (hors dépôt id=4)
- Dossiers Incomplets >= 50 Kwh Cumac
- Dossiers Standby >= 50 Kwh Cumac

**Comment by pboko** [comment]
Quel email envoyer??

**Comment by lindavte** [comment]
svn 11345 (branche qualification)

**Comment by lindavte** [comment]
svn 11346, 11347, 11348, 11349, 11350, 11351

**Comment by lindavte** [comment]
il reste à changer l'image de header de mail qui sera faite par jonathan et le mail dossiers incomplet et standby

**Comment by lindavte** [comment]
svn 11354 (changer l'image de header de mail)
