### ISSUE TITLE
Spécifications manquantes des pages ci-dessous

### ISSUE THREAD

**Issue by pboko** [vteco/pre#435]
- page login front
- guide énergie list
- guide énergie page
- nos partenaires
- témoignages
- nous contacter
- presse
- simulateur global
- perso / mes infos
- perso / dossier
- perso / nous contacter
- perso / PES
- homepage site entreprise
- page recap antargaz, finagaz (iframe)

**Comment by lindavte** [comment]
Home page de site entreprises

**Comment by pboko** [comment]
Il ne reste que:
- guide énergie page
- nos partenaires  => juste remettre les logos
- homepage site entreprise
