### ISSUE TITLE
Ajouter un nouveau champ title sur l'obligé, qui ne sert qu'à nous

### ISSUE THREAD

**Issue by pboko** [vteco/pre#44]
Ce champ nous sert uniquement à différencier les différents obligés AVIA ou VTE dans le backend, lorsqu'on affecte un obligé à un partenaire

**Comment by pboko** [comment]
Et dans le libellé du champ dans le formulaire, préciser "Nom dans le backend (non utilisé dans les documents)"

**Comment by lindavte** [comment]
svn 8468

**Comment by pboko** [comment]
Utiliser le champ :  
- en mode liste dans backend=>obligé
- dans select de choix d'obligé d'un partenaire (création + édition)

**Comment by lindavte** [comment]
svn 8479
