### ISSUE TITLE
A côté de la question "avis reçu", mettre un encart sur les justificatifs de revenus existants

### ISSUE THREAD

**Issue by pboko** [vteco/pre#456]
si le bénéficiaire possède d'autres dossiers, et que ces dossiers possèdent des justificatifs de revenus en PJ, il faut pouvoir proposer la visualisation, et idéalement l'ajout en un clic, de justificatifs au dosseir en cours.

"Il existe des justificatifs de revenus sur d'autres dossiers: 
- ...   visualiser - ajouter
- ...   visualiser - ajouter
- ...   visualiser - ajouter
  "

ces liens sont similaires à ce que nous avons fait sur la question du RGE

**Comment by lindavte** [comment]
Si absent afficher les justificatifs des autres dossiers de user
