### ISSUE TITLE
Changement de l'ordre des dates dans la fiche dossier extranet

### ISSUE THREAD

**Issue by pboko** [vteco/pre#46]
Mettre la date de l'attestation sur l'honneur du Pro avant la date de l'attestation sur l'honneur du bénéficiaire.

![image](https://cloud.githubusercontent.com/assets/1906061/6528239/ec3cae8a-c420-11e4-97b0-50d5b6554dea.png)

**Comment by lindavte** [comment]
Mettre la date de l'attestation sur l'honneur du bénéficiaire avant la date de l'attestation sur l'honneur du Pro.

**Comment by lindavte** [comment]
svn 8364
