### ISSUE TITLE
Page nous contacter

### ISSUE THREAD

**Issue by lindavte** [vteco/pre#461]

**Comment by VincentPrimeEnergie** [comment]
Page terminée

Seule différence avec le front global : 
J'ai du enlever le bloc contenant la ligne "<?php  include_component('blocs', 'calculPrime'); ?>" qui ne fonctionnait pas du a la différence de la route "simulator' qui attends un id ici

**Comment by VincentPrimeEnergie** [comment]
J'ai du modifier la partie "DEVENIR PARTENAIRE
(9h30 - 18h30 sans interruption)
BESOIN D'INFOS ? ENVOYEZ-NOUS UN MAIL !"

Qui ne tenait pas dans le template, a voir si il faut trouver un moyen de le remettre dedans ou si ce n'est pas necessaire
