### ISSUE TITLE
Style du sélecteur de sites

### ISSUE THREAD

**Issue by pboko** [vteco/pre#47]
![image](https://cloud.githubusercontent.com/assets/1906061/6553953/7dbe9210-c656-11e4-9b69-4f3c15af66ca.png)

Le nom dans les boutons est un peu flouté.
=> police: arial, couleur: blanc, text-shadow: supprimer

Et le lien 'professionnels' n'est pas aligné verticalement avec les boutons 
=> exemle de résolution: mettre display: inline-block et vertical-align: middle sur les deux (les boutons, et le lien).

**Comment by lindavte** [comment]
svn 8373
