### ISSUE TITLE
Pages Outils de gestion Antargaz 

### ISSUE THREAD

**Issue by lindavte** [vteco/pre#471]
- liste des avenant 
- Page envoi avenant par lot(formulaire, page de validation, page de résultat ) 
- Page ordre de reglement 
- Page dossiers prescripteurs
- Page liste prescripteurs
- Page prescripteur
- Page import partenaires 
  -Page prescripteur en attente de validation

**Comment by VincentPrimeEnergie** [comment]
liste des avenants OK;

Attente de confirmation du design

**Comment by VincentPrimeEnergie** [comment]
Page actions groupées et ordre de règlement OK

**Comment by VincentPrimeEnergie** [comment]
Toutes les pages sont faites

Restes juste un test a faire sur les affichages conditionnels des différentes pages et a me filer un excell pour tester la page /import-des-partenaires/felicitations accessible apres l'upload
