### ISSUE TITLE
Page de création de partenaires : afficher en ajax des selects permettant de choisir le parent

### ISSUE THREAD

**Issue by pboko** [vteco/pre#513]
S'arrêter lorsque le partenaire n'a pas de petits-enfants
Mettre un champ 'parent_id' caché dans le formualire, qui est rempli lorsque le dernier select est modifié

A la modification d'un select:
- soit le partenaire choisi a des petits-enfants, et on affiche un nouveau select
- soit il n'en a pas, et on remplit parent_id

**Comment by lindavte** [comment]
svn 12953
