### ISSUE TITLE
Page générique d'un partenaire enfant

### ISSUE THREAD

**Issue by pboko** [vteco/pre#524]
Elle existe actuellement pour un prescripteur antargaz.
On conserve les mêmes stats qu'actuellement. 

Il faudra rajouter la liste des utilisateurs créteurs, et leurs stats également.

Les partenaires enfants ayant eux-mêmes des enfants sont cliquables => on arrive sur la même page, mais pour le petit-fils

**Comment by VincentPrimeEnergie** [comment]
Manque l'affichage des partenaires enfants si existant
