### ISSUE TITLE
Ajout au menu "vos utilisateurs" et "vos partenaires"

### ISSUE THREAD

**Issue by pboko** [vteco/pre#525]
uniquement si le partenaire a des enfants
![image](https://cloud.githubusercontent.com/assets/1906061/15009374/517472ec-11e6-11e6-9349-4505e98fd5c0.png)

**Comment by lindavte** [comment]
Affichage conditionnel (si le partenaire peut avoir d'enfants on affiche vos utilisateurs et vos partenaires )
