### ISSUE TITLE
Mettre les pages "mot de passe oublié" en iframe

### ISSUE THREAD

**Issue by pboko** [vteco/pre#53]
Mettre en place toute la mécanique.
Restaurer les liens "j'ai oublié mon mot de passe"
Supprimer les éléments de langage spécifiques à primes énergie.fr, car on va s'en servir pour Antargaz

**Comment by pboko** [comment]
Ne pas oublier de vérifier et de modifier au besoin l'email envoyé

**Comment by lindavte** [comment]
svn 8374, 8375, 8380, 8381, 8382, 8383
