### ISSUE TITLE
Iframes VEE sur espace pro

### ISSUE THREAD

**Issue by VincentPrimeEnergie** [vteco/pre#583]

**Comment by pboko** [comment]
Tu pourras ajouter un onglet sur l espace pro. Avec nos simulateurs.
Je ne sais plus si tu l as passe.

Avec un message. 
Votre espace pro s enrichit: profitez désormais pour vous aider à signer de nouvelles ventes et conseiller vos clients.
- prévoir envoie newletter à nos partenaires quand realise

**Comment by pboko** [comment]
Rajouter une page par type d'iframe, le routing détermine un type mais c'est la même action
L'action décide de l'URL de l'iframe = fonction(type)

menu de gauche : liste tous les types d'iframes, et sélectionne celle en cours

**Comment by VincentPrimeEnergie** [comment]
En attente la bannière ISO 1€
