### ISSUE TITLE
Iframe PEE : customiser l'email d'incitation

### ISSUE THREAD

**Issue by pboko** [vteco/pre#599]
But : ne plus avoir de mentions à la marque primesenergie.fr, uniquement à l'obligé vostravauxeco

PrimesEnergie.fr (société Vos Travaux Eco) et son partenaire Primes éco énergie 
=> Primes éco énergie (société Vos Travaux Eco)

Au passage : résoudre la phrase 
 Primes éco énergie, . Nous sommes heureux de vous accompagner dans votre projet :

(il manque "pour votre projet <b>isolation des murs</b>)

Au passage:
résoudre le changement de police 
![image](https://cloud.githubusercontent.com/assets/1906061/16266579/e19dadb4-3885-11e6-8ba0-751bf5f903f2.png)

**Comment by pboko** [comment]
Logo:
recopier celui uploadé dans /uploads/partner/primesecoenergie.png (ou équivalent)
dans /images.new/emails/logo-pee.png

**Comment by VincentPrimeEnergie** [comment]
Manque le logo j'ai pas les droits S3
