### ISSUE TITLE
Utiliser quotation_date plutôt que work_start_date

### ISSUE THREAD

**Issue by pboko** [vteco/pre#6]
Vérifier que les webservice des travaux P3 utilisent bien quotation_date, en particulier pour les travaux:
BAR-TH-118
BAR-TH-104
BAR-TH-150
BAT-TH-113

Et s'assurer que c'est bien cette date qui est utilisée dans l'API d'import de dossiers

**Comment by pboko** [comment]
Il faudra également modifier les sites QPR et VEE pour qu'ils utilisent bien cette date, et plus work_start_date

**Comment by lindavte** [comment]
Svn VEE : 2688; 2689
SVN SIMULATOR : 8346
SVN QP : 8347

**Comment by lindavte** [comment]
Svn Prime : 8348
