### ISSUE TITLE
Extranet: pouvoir effacer des historiques depuis la fiche dossier

### ISSUE THREAD

**Issue by pboko** [vteco/pre#61]
!!!!!   UNIQUEMENT  pour les repsonsables SAV  !!!!!!
D'abord rajouter un champ en base 'is_deleted' sur contact_history et history. Par défaut, à 0

Ensuite dans l'affichage, ne mettre que les entrées  d'historique où is_deleted = 0.

Enfin rajouter une croix à côté de chaque entrée d'historique (contact_history et history), qui permet au responsable de service client de marquer une entrée d'historique comme supprimée (is_deleted = 1)

**Comment by lindavte** [comment]
svn : 8420, 8421, 8422, 8423, 8427, 8429
