### ISSUE TITLE
Fiches manquantes

### ISSUE THREAD

**Issue by pboko** [vteco/pre#612]
Comme indiqué, après vérification du 22ème arrêté : 

1/Il comporte une modification des fiches AGRI-UT-102 et BAT-TH-112 (changement du forfait et des ASH)
qui sont applicables aux opérations standardisées d’économies d’énergie engagées à partir du 1er juillet 2016.

2/ Création de 7 nouvelles fiches , pour lesquelles je te laisse voir si tu souhaites les intégrer à l'offre au regard de la valeur des forfaits cumac.

Afin de faciliter le travail de l'équipe IT, je t'ai préparé un dossier avec les nouvelles fiches.

**Comment by pboko** [comment]
POINT D’INFOS du Club C2E
Cher Adhérent

Le 22è arrêté définissant des opérations standardisées d’économies d’énergie est paru au J.O du 10 juin dernier. lien vers l’arrêté sur Legifrance  (trop lourd pour être mailé).

Ce texte modifie les fiches AGRI-UT-102 et BAT-TH-112 (déjà révisées) pour les opérations engagées à partir du 1er juillet 2016
Il valide la révision de 7 fiches ; pour celles-ci vous trouverez, ci-joint,  le tableau de correspondance avec les fiches de 2e période.

Les fiches de calcul correspondantes sont téléchargeables sur l’espace membres de notre site.(1)

Les powerpoints de notre journée CEE du 10 mai dernier sont téléchargeables sur notre site (1)

**Comment by lindavte** [comment]
J'ai fini la révision des fiches : AGRI-UT-102, BAT-TH-112 et BAR-EQ-111

**Comment by lindavte** [comment]
bat-th-109, bat-th-108, bat-th-122, bat-th-134 => OK

**Comment by lindavte** [comment]
bat-eq-123, bat-eq-125, bat-eq-130
