### ISSUE TITLE
Créer un formulaire d'ajout d'avis

### ISSUE THREAD

**Issue by pboko** [vteco/pre#627]
Reprend le travail existant sur les "étoiles" des témoignages
Crée un widget par question, de type étoile

Nouvelle page dédiée à la notation d'un artisan, dans l'espace perso
Mettre un minimum de style pour la page de formulaire

**Comment by JonathanVTE** [comment]
Su un modèle de ce type.

Avec les quatre critères suivants:
1. Rapport qualité / prix
2. Respect des délais annoncés
3. Professionnalisme
4. Disponibilité / accueil de l'artisan

[image: Images intégrées 1]

[image: primes énergie.fr]
_Nicolas MOULIN *_  -  Fondateur dirigeant*
Tel. : 06 70 07 38 76
3 rue de Palestro, 75002, Paris, France
Primes énergie.fr http://www.primesenergie.fr/ / _Groupe VOS TRAVAUX ECO_
*Retrouvez nous sur     *[image: Facebook]
https://www.facebook.com/primesenergie.fr  [image: Twitter]
https://twitter.com/PrimesEnergie  [image: Google +]
https://plus.google.com/u/0/107942683947756419203

Regardez la nouvelle vidéo de Primes Énergie directement sur Youtube !
http://www.youtube.com/watch?feature=player_embedded&v=CiLqfsQYkCs
