### ISSUE TITLE
Site entreprise: afficher TTC plutôt que HT

### ISSUE THREAD

**Issue by pboko** [vteco/pre#63]
![image](https://cloud.githubusercontent.com/assets/1906061/6602906/dfa877ec-c81e-11e4-8205-782df5fee69c.png)

Dans la première page de résultat. On va toujours afficher un montant TTC pour gonfler artificiellement le montant de la prime.

Il faire cela uniquement sur entreprises.primesenergie.fr directement, et pas dans les iframes

**Comment by lindavte** [comment]
svn 8412
