### ISSUE TITLE
Réparer le formulaire de contact pro.primesenergie.fr

### ISSUE THREAD

**Issue by JonathanVTE** [vteco/pre#64]
http://pro.primesenergie.fr/enterprise.php/nous-contacter

Le formulaire de contact ne marche pas.

Il faut le réparer et s'assurer qu'il envoie bien les e-mails à l'adresse partenaire@primesenergie.fr (cette adresse doit aussi être ajouter dans le bloc de texte à droite en remplacement de contact@primesenergie.fr)

![bugs bokobza](https://cloud.githubusercontent.com/assets/11160254/6602941/1d6ca49a-c81f-11e4-8d6e-08129c81ab45.PNG)

**Comment by nicolasvte** [comment]
```
                                                                                  Très très important.Quel dommage de perdre d éventuelles demandes                                                                                                                                                                                                                                                                                                                                        Nicolas MOULINPDG, Vos Travaux EcoMob: 06 70 07 38 76www.vostravauxeco.fr                                                                                                                                                                                                                 De: JonathanVTEEnvoyé: mercredi 11 mars 2015 18:49À: vteco/preRépondre à: vteco/preObjet: [pre] Réparer le formulaire de contact pro.primesenergie.fr (#64)http://pro.primesenergie.fr/enterprise.php/nous-contacter
```

Le formulaire de contact ne marche pas.

Il faut le réparer et s'assurer qu'il envoie bien les e-mails à l'adresse partenaire@primesenergie.fr (cette adresse doit aussi être ajouter dans le bloc de texte à droite en remplacement de contact@primesenergie.fr)

—Reply to this email directly or view it on GitHub.

**Comment by lindavte** [comment]
svn 8410
