### ISSUE TITLE
Groupama: mettre à jour les contenus PRE et VEE (nouveaux taux)

### ISSUE THREAD

**Issue by pboko** [vteco/pre#65]
L'ancien exemple type était:
- 3000 €
- 60 mois

Il nous faut:
- TAEG
- Taux nominal
- Mensualités
- Montant total dû
- Montant total des intérêts

Demander nouveaux taux d'assurance facultative (montant sur 60 mois)
Demander TAEA (Taux Annuel Effectif de l'Assurance)

**Comment by lindavte** [comment]
svn 8464
