### ISSUE TITLE
Interface pro : si trop d'enfants, afficher un lien "voir tous les professionnels"

### ISSUE THREAD

**Issue by pboko** [vteco/pre#67]
C'est surtout pour les architecteurs, qui ont une centaine d'enfants. On souhaite mettre tous les liens dans la page, mais n'en afficher que 20 environ (tester graphiquement), et masquer les autres.

Au clic sur le lien "voir tous les professionnels", on affiche tous les autres enfants.

=> Non prioritaire

**Comment by lindavte** [comment]
svn 8461
