### ISSUE TITLE
Réparer la recherche extranet

### ISSUE THREAD

**Issue by pboko** [vteco/pre#7]
Faire en sorte qu'elle ne splitte plus les mots => on impose un seul mot dans la recherche. S'il y a plusieurs mots, on ne prend en compte que le premier

Mettre également un nombre de lettres minimum, afin d'exclure les recherches sur "le", "la", "et".
A 4 caractères

Il faudra faire ensuite des tests de performance sur des mots très communs, comme "jean" => vérifier que ça ne fasse plus saturer le serveur

**Comment by lindavte** [comment]
Svn revision : 8272, 8273
