### ISSUE TITLE
Site mobile: l'espace perso est incomplet

### ISSUE THREAD

**Issue by pboko** [vteco/pre#70]
Il faudrait remettre un menu, qui permette de faire une nouvelle demande. Et éventuellement de se déconnecter

Actuellement: 
![image](https://cloud.githubusercontent.com/assets/1906061/6637023/bdb80758-c975-11e4-9965-8e1c4f8f9e87.png)
On est enfermés dans cette page

**Comment by lindavte** [comment]
svn 8457
