### ISSUE TITLE
Envoyer la raison d'incomplétude au client également

### ISSUE THREAD

**Issue by pboko** [vteco/pre#72]
Lorsqu'on envoie un email incomplet à l'artisan, le bénéficiaire reçoit un mail dédié de type : "nous avons contacté votre artisan directement, pour résoudre le problème sur votre dossier".

Il serait souhaitable que le client reçoive également la raison d'incomplétude. Quitte à coller directement le message généré initialement par la BDD

**Comment by lindavte** [comment]
svn 8443
