### ISSUE TITLE
Evolutions QPR sur la requalif et les relances

### ISSUE THREAD

**Issue by pboko** [vteco/pre#744]
Quelleprime.fr
Front
- ajout d'une case "j'accepte de recevoir offres commerciales..." 
- vente auto à Quotatis de tout le volume avec case cochée
- modifier l'email de relance: lister "nos" offres Cash
- lien "unsubscribe" sur les emails de relance

Back
- modifier la structure des listes de rappel
- bloquer les comptes quelleprime "fausse demande" et/ou "mauvais coord."
- nouveau statut "Lead PEM" 
- réaffecter ce statut rétroactivement aux sims existantes (si possible)
- masquer les contacts déjà rappelés

**Comment by lindavte** [comment]
Front

ajout d'une case "j'accepte de recevoir offres commerciales..." => OK
vente auto à Quotatis de tout le volume avec case cochée => OK

**Comment by lindavte** [comment]
Quelleprime.fr
Front

ajout d'une case "j'accepte de recevoir offres commerciales..." => OK
vente auto à Quotatis de tout le volume avec case cochée => OK 
modifier l'email de relance: lister "nos" offres Cash => OK 
lien "unsubscribe" sur les emails de relance => OK

**Comment by lindavte** [comment]
Back

modifier la structure des listes de rappel => OK 
nouveau statut "Lead PEM" => OK
réaffecter ce statut rétroactivement aux sims existantes (si possible) => OK
masquer les contacts déjà rappelés => OK
