### ISSUE TITLE
Emailing trustpilot après l'envoi du chèque

### ISSUE THREAD

**Issue by pboko** [vteco/pre#9]
AUjourd'hui on incite les bénéficiaires de pimres à déposer un  témoignages sur primesenergie.fr suite à l'envoi de leur chèque. Mais pas sur trustpilot.

Il faudrait il faut envoyer un emailing qui incite les gens à publier un témoignage sur trustpilot quelques jours après l'envoi du chèque, disons 5.

Et enlever le lien de témoignage actuel sur primesenergie (je crois qu'il est dans  le mail de chèque envoyé)

**Comment by pboko** [comment]
Titre de l'email:      Primes énergie.fr: Partagez votre avis !

**Comment by lindavte** [comment]
svn revision : 8316

**Comment by lindavte** [comment]
svn revision : 8317
