### ISSUE TITLE
Extranet : Prime TTC = Prime HT quand client concerné par la TVA

### ISSUE THREAD

**Issue by JonathanVTE** [vteco/pre#97]
Dossier d'exemple : 
http://extranet.primesenergie.fr/extranet.php/dossiers/VTE-A1E26B

Peut importe le fonctionnement du domain entreprise, pour les clients concernés par la TVA, le montant TTC doit être correctement calculé et être différent du montant HT.

**Comment by lindavte** [comment]
Le dossier n'est pas un dossier entreprise
